name: Dean Colin Marcial
favicon: null
layout_spectrum: 0.2556235638912767
typography_spectrum: 0.8958603045903146
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.09846923383884132
  lightness: 0.5001161783002317
  saturation: 0.4792326078750193
  rhythmicContrast: 0.8813588132616132
purpose: []
